version: '3'

services:
  config-server:
    image: config-server-docker.jar
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/gokulsankar715/HealthCareUserModule
    ports:
      - 8888:8888
  vault:
    image: vault
    ports:
      - '8200:8200'
    restart: always
    environment:
      - 'VAULT_ADDR=http://localhost:8200'
      - 'VAULT_DEV_ROOT_TOKEN_ID=00000000-0000-0000-0000-000000000000'
      - 'dev'
    cap_add:
      - IPC_LOCK
  consul:
    image: consul
    ports:
      - '8500:8500'
    command: 'agent -server -bootstrap-expect 1 -ui -client 172.22.0.6'
  redis:
    image: redis
    ports:
      - '6379:6379'  
  localhost:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: world
      MYSQL_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      
  healthcare-patient:
    image: healthcare-patient-docker.jar
    ports:
      - 9001:9094
    environment:
      DB_HOST: localhost
      DB_DATABASE: world
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/world
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - config-server
      - vault
      - localhost
      - consul
